### ISSUE TITLE
I'd like to volunteer!

### ISSUE THREAD

**Issue by jacobroufa** [cascadiajs/2016.cascadiajs.com#1]
Help me help you. What can I do to volunteer for CascadiaJS 2016?

**Comment by davethegr8** [comment]
Hi! Are you interested in anything in particular?

**Comment by jacobroufa** [comment]
Hey @davethegr8! I was talking with @hackygolucky and @KatieK2 at JSConf and basically I have aspirations to run my own conference sometime in the next couple years. In order to learn how to do that I'd like to volunteer at as many other conferences as I can, to whatever capacity they want me or will allow me. I helped at Nodevember last month and worked on registration, general organization and room monitor duties. I also run a meetup and as a result I feel like I can do or can learn to do most anything with regards to organizing stuff. Your conference seems like an awesome one to put on my list. I'd love to help in whatever way I can. :+1:

**Comment by davethegr8** [comment]
Awesome, glad to hear! We haven't really started planning anything yet, but we are getting started soon. I'd suggest signing up for the newsletter (on 2016.cascadiajs.com) / following us on twitter (@cascadiajs) so you know what's going on and I'll make sure we reach out to you when we start making plans.

**Comment by jacobroufa** [comment]
:smile_cat:
