### ISSUE TITLE
Improve font-rendering of white/tan text

### ISSUE THREAD

**Issue by jdsteinbach** [cascadiajs/2016.cascadiajs.com#15]
Hi, @davethegr8! Love the site; it'd be just a bit more legible with some CSS for antialiasing the light text on a dark background. I'm happy to make that change. See attached screenshot (original on left, antialiased on the right).

![Original on left, upgrade on right](https://cloud.githubusercontent.com/assets/1395360/15260624/17c61fec-1915-11e6-85ff-d7791ff94593.jpg)

If this is an upgrade you'd like, how would you like a PR? Should I fork the repo to my account, or submit a branch right on this repo?

Thanks! Looking forward to the conference in August

**Comment by davethegr8** [comment]
Thanks! If you want to fork & open a pr that's great!

@zachattack will probably want to have input on this.

**Comment by zachattack** [comment]
@jdsteinbach send the PR through. Interested to see the fix :)

**Comment by jdsteinbach** [comment]
PR here: https://github.com/cascadiajs/2016.cascadiajs.com/pull/16

Thanks!

**Comment by zachattack** [comment]
This was merged!
