### ISSUE TITLE
News / blog feed

### ISSUE THREAD

**Issue by davethegr8** [cascadiajs/2016.cascadiajs.com#3]
We'll need a news system for the 2016 website. We had a reasonable system last year, so we'll want to bring that over to start with. 

The previous issue was: https://github.com/cascadiajs/2015.cascadiajs.com/issues/206

For 2016:

It will live here: http://2016.cascadiajs.com/news and should be build based on this tutorial: http://harpjs.com/recipes/blog-posts-list

Our news data will need title, url/slug, publish date, and abstract field (sort of like intro).

We'll want an index page listing our articles (probably don't need to paginate), as well as an rss feed.

Off of the index or rss we'll link to the full article url.

The website lives here: https://github.com/cascadiajs/2016.cascadiajs.com/ and should have everything needed to get it up and running. (npm install, npm start)

**Comment by toddself** [comment]
I'm on it!

**Comment by toddself** [comment]
Should the website repo be changed to 2016.cascadiajs.org?

**Comment by davethegr8** [comment]
Super!

We're still using the .com for now, but I did change the last link to 2016.cascadiajs.com.

**Comment by davethegr8** [comment]
See #7
