### ISSUE TITLE
Staff page

### ISSUE THREAD

**Issue by davethegr8** [cascadiajs/2016.cascadiajs.com#4]
Similar to 2015, (https://github.com/cascadiajs/2015.cascadiajs.com/tree/master/website/public/staff) we will need a staff page.

We will have different levels of staff:
- Organizers
- Curators
- Coordinators
- Volunteers
- Contributors

Each staff person may list their name, avatar / profile pic, and any contact information they'd like to share. We will also have a title listed for people in the Coordinator/Curator/Organizer roles.

For any staff that deal directly with participants, we want the profile pic to be identifiable, so that it is easier for participants to locate and identify important people.

For people who make contributions to the website / github project, we want to have their github username, avatar, and link to their profile.

**Comment by KatieK2** [comment]
Updates for Katie:

New title: 
Curator: CascadiaCSS

Add Github link:
KatieK2 / https://github.com/KatieK2/

Reuse Twitter link:
KatieK2 / https://twitter.com/KatieK2

Please do not publish email.

New picture: 
![headshot-square-sm](https://cloud.githubusercontent.com/assets/3174626/13930997/918c9184-ef5e-11e5-883b-99cc7f1e052d.jpg)

**Comment by lrlna** [comment]
Irina's interwebz:

Twitter: [_lrlna](https://twitter.com/_lrlna)

Github: [lrlna](https://github.com/lrlna)

Please do not put my email.

Photo:
![img_4618-cropped](https://cloud.githubusercontent.com/assets/8107784/13931491/cad30232-ef60-11e5-8a43-0c869a343e31.JPG)

**Comment by KatieK2** [comment]
Probably OK to close this - the staff page has been fine so far and we're at conf-time.
