### ISSUE TITLE
Node Schedule page links to CSS Schedule Page

### ISSUE THREAD

**Issue by KatieK2** [cascadiajs/2016.cascadiajs.com#40]
Each day's schedule page links to the day(s) before or after it - nice!

But the Node Day schedule page (http://2016.cascadiafest.org/node/)'s "previous day" link goes to CSS day (and has the CSS styling) when it should go to Browser day.

(Sorry for filing a bug instead of just fixing it myself.)

**Comment by davethegr8** [comment]
oh i fixed this
