### ISSUE TITLE
Do not use `after_success` for deployment

### ISSUE THREAD

**Issue by BanzaiMan** [cascadiajs/2016.cascadiajs.com#6]
https://github.com/travis-ci/travis-ci/issues/5813#issuecomment-200493965

The use of `after_success` to deploy your site is not recommended, as anyone can change the content of your site by just opening a PR. Please consider using our [deployment](https://docs.travis-ci.com/user/deployment/) scheme instead.

**Comment by davethegr8** [comment]
Thanks! 

Fixed in https://github.com/cascadiajs/2016.cascadiajs.com/commit/648dd32ac79bf7b4e4720bebc6e63a5948802542

**Comment by kennethormandy** [comment]
@BanzaiMan Thanks for the update about this, that’s my misunderstanding. The [Surge docs for Travis](https://surge.sh/help/integrating-with-travis-ci) should probably be updated accordingly. @sintaxi
